# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9326a13a26c092b205f950f0ecfe297259c56c496acefd227c7ff29ffa8fecd1f90c78716010bc5be59060ad70161455a208e80054bb8cb675ea49125861e792

test:
  secret_key_base: 791b9bdf46cfd3b5e1c13202cbf9689436c6e5d05cc0ed57081b08745030f8bb44f0628642c47dae488554af95205c52a6b9a596e3362c2a6bb84ccbaa52d229

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
